# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [User1, user2]
patreon: # Replace with a single Patreon peterdaniel24
open_collective: # Replace with a single Open Collective peterdaniel24
ko_fi: # Replace with a single Ko-fi peterdaniel24
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay peterdaniel24
issuehunt: # Replace with a single IssueHunt peterdaniel24
otechie: # Replace with a single Otechie peterdaniel24
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
